version: "3.8"

services:
  sqlserver:
    container_name: sqlserver2019
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    user: '0:0'
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: J4V1t024
      MSSQL_PID: Express
    volumes:
      - ./Databases/sqlserver2019:/var/opt/mssql